### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by 8twinni8** [MattMoony/d4v1d#1]
You can not grab a person, who has above 1k Followers/Followings.
Really bad performance.

**Comment by MattMoony** [comment]
Might have been an issue previously, personally, I'm not experiencing this, however. So, I'm going to close this 😬 
Just grabbed all followers of a 2k+ account and it didn't even take long 🤷 ^^

Please, feel free to elaborate, if you're still experiencing this issue!

_- Matthias_
